# Site settings
title: Mengxuan Shi
description: A simple blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mengxuan Shi
user_description: I'm a Computer Science student at Carleton University.  <br/>I'm chasing my dream to become a software engineer.
user_title: 
email: mengxuanshi@gmail.com
# twitter_username: lorem_ipsum
github_username: men9xuan
# gplus_username:  lorem_ipsum
linkedin_username: mengxuan-s-85800677

# Google-analytics


exclude: ['package.json', 'src' , 'node_modules']
